import { useQuery } from '@tanstack/react-query'
import { BarChart3, CalendarCheck2, ChartNoAxesCombined, CircleAlert, DoorOpen, UserRound } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { reportsService } from '../../services/reportsService'
import { usePageTitle } from '../../hooks/usePageTitle'
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card'
import { LoadingState } from '../../components/common/LoadingState'
import { ErrorState } from '../../components/common/ErrorState'
import { EmptyState } from '../../components/common/EmptyState'
import { StatusBadge } from '../../components/common/StatusBadge'
import { getDayLabel, formatTime } from '../../lib/utils'

const colors = ['#4f46e5', '#06b6d4', '#10b981', '#f59e0b', '#ec4899', '#8b5cf6', '#f97316', '#14b8a6']

export function Reports() {
  usePageTitle('التقارير')
  const query = useQuery({ queryKey: ['reports'], queryFn: reportsService.getReport })
  if (query.isLoading) return <LoadingState rows={8} />
  if (query.isError) return <ErrorState error={query.error} onRetry={() => query.refetch()} />
  const data = query.data
  return <div className="page-enter"><div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[.16em] text-primary">تحليل الأداء</p><h1 className="text-2xl font-black tracking-tight sm:text-3xl">التقارير والبيانات</h1><p className="mt-1 text-sm leading-6 text-muted-foreground">قراءة تشغيلية مبنية على المحاضرات المسجلة فعليًا في Supabase.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReportStat label="إجمالي السجلات" value={data.total} icon={ChartNoAxesCombined} tone="bg-indigo-500/10 text-indigo-600" /><ReportStat label="محاضرات نشطة" value={data.active} icon={CalendarCheck2} tone="bg-emerald-500/10 text-emerald-600" /><ReportStat label="محاضرات ملغاة" value={data.canceled} icon={CircleAlert} tone="bg-rose-500/10 text-rose-600" /><ReportStat label="القاعات المستخدمة" value={data.byHall.length} icon={DoorOpen} tone="bg-amber-500/10 text-amber-600" /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><ReportChart title="المحاضرات حسب اليوم" subtitle="المحاضرات النشطة فقط" data={data.byDay} bar /><ReportChart title="المحاضرات حسب القسم" subtitle="التوزيع على الاختصارات الأكاديمية" data={data.byDepartment} /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><RankingCard title="أكثر القاعات استخدامًا" icon={DoorOpen} data={data.byHall} empty="لا توجد بيانات قاعات." /><RankingCard title="توزيع المحاضرات حسب المدرس" icon={UserRound} data={data.byInstructor} empty="لا توجد بيانات مدرسين." /></div><Card className="mt-5"><CardHeader><CardTitle>سجل المحاضرات الملغاة</CardTitle><p className="mt-1 text-xs text-muted-foreground">الإلغاء يحافظ على السجل ولا يحذفه من النظام.</p></CardHeader><CardContent>{data.canceledRows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="px-4 py-3">اليوم</th><th className="px-4 py-3">الوقت</th><th className="px-4 py-3">المادة</th><th className="px-4 py-3">القاعة</th><th className="px-4 py-3">الدفعة</th><th className="px-4 py-3">الحالة</th></tr></thead><tbody className="divide-y divide-border">{data.canceledRows.map((row) => <tr key={row.id}><td className="px-4 py-3">{getDayLabel(row.day_of_week)}</td><td className="px-4 py-3 font-mono text-xs">{formatTime(row.start_at)} — {formatTime(row.end_at)}</td><td className="px-4 py-3 font-semibold">{row.subject?.title || '—'}</td><td className="px-4 py-3">{row.hall?.title || '—'}</td><td className="px-4 py-3">{row.batch?.department_abbr} — {row.batch?.level?.title}</td><td className="px-4 py-3"><StatusBadge status="canceled" /></td></tr>)}</tbody></table></div> : <EmptyState title="لا توجد محاضرات ملغاة" description="لم يتم تسجيل أي عملية إلغاء في البيانات الحالية." />}</CardContent></Card></div>
}

function ReportStat({ label, value, icon: Icon, tone }) { return <Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-xs font-bold text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div></CardContent></Card> }
function ReportChart({ title, subtitle, data, bar = false }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{subtitle}</p></CardHeader><CardContent>{data.length ? <ResponsiveContainer width="100%" height={280}>{bar ? <BarChart data={data} layout="vertical" margin={{ top: 4, right: 10, left: 10, bottom: 0 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" opacity={.2} /><XAxis type="number" allowDecimals={false} axisLine={false} tickLine={false} fontSize={11} /><YAxis type="category" dataKey="name" width={78} axisLine={false} tickLine={false} fontSize={11} /><Tooltip content={<ReportTooltip />} /><Bar dataKey="value" name="المحاضرات" radius={[0, 6, 6, 0]} fill="#4f46e5" /></BarChart> : <PieChart><Pie data={data.slice(0, 8)} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={60} outerRadius={96} paddingAngle={3}>{data.slice(0, 8).map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip content={<ReportTooltip />} /></PieChart>}</ResponsiveContainer> : <EmptyState title="لا توجد بيانات كافية" description="ستظهر النتائج عند توفر محاضرات نشطة." />}{!bar && data.length ? <div className="flex flex-wrap justify-center gap-x-4 gap-y-2">{data.slice(0, 8).map((item, index) => <span key={item.name} className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} />{item.name} ({item.value})</span>)}</div> : null}</CardContent></Card> }
function RankingCard({ title, icon: Icon, data, empty }) { return <Card><CardHeader className="flex-row items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></div><div><CardTitle>{title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">ترتيب تنازلي حسب عدد المحاضرات</p></div></CardHeader><CardContent>{data.length ? <div className="space-y-3">{data.slice(0, 6).map((item, index) => <div key={item.name} className="flex items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted text-xs font-black">{index + 1}</span><div className="min-w-0 flex-1"><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate font-bold">{item.label || item.name}</span><span className="font-black text-primary">{item.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-to-l from-primary to-cyan-400" style={{ width: `${Math.max(8, (item.value / data[0].value) * 100)}%` }} /></div></div></div>)}</div> : <EmptyState title={empty} description="لا توجد سجلات متاحة للعرض." />}</CardContent></Card> }
function ReportTooltip({ active, payload, label }) { if (!active || !payload?.length) return null; return <div className="rounded-xl border border-border bg-card px-3 py-2 text-xs shadow-xl"><p className="font-bold">{label || payload[0].name}</p><p className="mt-1 text-primary">{payload[0].value} محاضرة</p></div> }
